version: "3"

services:
  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    env_file: .env
    ports:
      - "8080:3000"
    environment:
      - HOST=0.0.0.0
      - NODE_IP=0.0.0.0
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=outline
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
